#%Module1.0
if {! [info exists ::env(MPIHOME)]} {
  puts stderr "Need to load an mpi module before loading nco"
  exit 1
}
foreach {x} [glob -directory /opt/nco/COMPILER -tails *] {
  if {[regexp $x $::env(MPIHOME)]} {
    set mpi $x
    break
  }
}
if {! [info exists mpi]} {
  if {[ regexp ScaleMP $::env(MPIHOME)]} {
      set mpi vsmp
  }
}
if {! [info exists mpi]} {
  puts stderr "No supported MPI flavor found"
  exit 1
}
foreach {x} [glob -directory /opt/nco/COMPILER/$mpi -tails *] {
  if {[regexp $x $::env(MPIHOME)]} {
    set network $x
    break
  }
}
if {! [info exists network]} {
  if {[ regexp ScaleMP $::env(MPIHOME)]} {
      set network ib
  }
}
if {! [info exists network]} {
  puts stderr "No supported network found"
  exit 1
}
module-whatis "nco"
module-whatis "Version: VERSION" 
module-whatis "Description: nco"
module-whatis "Compiler: COMPILER" 
set ncoHome /opt/nco/COMPILER/$mpi/$network
setenv NCOHOME $ncoHome
prepend-path PATH $ncoHome/bin
prepend-path LD_LIBRARY_PATH $ncoHome/lib
prepend-path LIBPATH $ncoHome/lib
setenv NCOHOME $ncoHome
prepend-path PATH $ncoHome/bin
prepend-path LD_LIBRARY_PATH $ncoHome/lib
prepend-path LIBPATH $ncoHome/lib
