#%Module1.0
module-whatis "netcdf"
module-whatis "Version: VERSION" 
module-whatis "Description: netcdf"
module-whatis "Compiler: COMPILER" 
set netcdfHome /opt/netcdf/VERSION/COMPILER
setenv NETCDFHOME $netcdfHome
prepend-path PATH $netcdfHome/bin
prepend-path LD_LIBRARY_PATH $netcdfHome/lib
prepend-path LIBPATH $netcdfHome/lib
set ncoHome /opt/nco/COMPILER
setenv NCOHOME $ncoHome
prepend-path PATH $ncoHome/bin
prepend-path LD_LIBRARY_PATH $ncoHome/lib
prepend-path LIBPATH $ncoHome/lib
