#%Module1.0

set compilernames [regexp -all -inline {\S+} [regsub -all {/\S*} "ROLLCOMPILER" ""]]

module-whatis "netcdf-serial"
module-whatis "Version: VERSION"
module-whatis "Description: netcdf-serial"
module-whatis "Compiler: $compilernames"

# Figure out the applicable compiler--either the one whose module was loaded
# when this modulefile was loaded or the one with the most-recently-loaded
# module.  Report an error if neither applies.
if [info exists env(NETCDFHOME)] {
  foreach {compiler} $compilernames {
    if {[string first "/$compiler" $::env(NETCDFHOME)] >= 0} {
      break
    }
  }
} elseif [info exists env(LOADEDMODULES)] {
  foreach {module} [split $::env(LOADEDMODULES) :] {
    set module [lindex [split $module /] 0]
    if {[regexp [format {%s(/|\s|$)} $module] $compilernames]} {
      set compiler $module
    }
  }
}
if { ! [info exists compiler] } {
  puts stderr "Need to load a compiler module first"
  exit 1
}

set netcdfHome /opt/netcdf/VERSION/$compiler/serial
setenv NETCDFHOME $netcdfHome
prepend-path PATH $netcdfHome/bin
prepend-path LD_LIBRARY_PATH $netcdfHome/lib
prepend-path LIBPATH $netcdfHome/lib
module load hdf5-serial
