#%Module1.0
if {[string equal "VERSION" "3.6.2"]} {
  # No MPI support in older version
  set netcdfHome /opt/netcdf/VERSION/ROLLCOMPILER
  set ncoHome [lindex [glob /opt/nco/ROLLCOMPILER/*] 0]
} else {
  module-whatis "netcdf/nco"
  module-whatis "Version: VERSION"
  module-whatis "Description: netcdf"
  module-whatis "Compiler: COMPILERNAME"
  module-whatis "MPI Flavors: ROLLMPI"
  if {! [info exists ::env(MPIHOME)] || ! [info exists ::env(LOADEDMODULES)]} {
    puts stderr "Need to load an mpi module before loading netcdf"
    exit 1
  }
  foreach {x} [list ROLLMPI] {
    # Look for flavor in LOADEDMODULES, delimited by colon or end of string.
    # Can also be followed by / (version number).
    if {[regexp [format {[:^]%s[:/$]} $x] $::env(LOADEDMODULES)]} {
      set mpi $x
      break
    }
  }
  if {! [info exists mpi]} {
    puts stderr "No supported MPI flavor found"
    exit 1
  }
  set netcdfHome /opt/netcdf/VERSION/ROLLCOMPILER/$mpi
  set ncoHome /opt/nco/ROLLCOMPILER/$mpi
}
setenv NETCDFHOME $netcdfHome
prepend-path PATH $netcdfHome/bin
prepend-path LD_LIBRARY_PATH $netcdfHome/lib
prepend-path LIBPATH $netcdfHome/lib
setenv NCOHOME $ncoHome
prepend-path PATH $ncoHome/bin
prepend-path LD_LIBRARY_PATH $ncoHome/lib
prepend-path LIBPATH $ncoHome/lib
if {! [string equal "VERSION" "3.6.2"]} {
  module load hdf5
}
